import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { 
  Upload, 
  FileText, 
  Sparkles, 
  Download, 
  Trash2,
  Brain,
  MessageSquare,
  ListChecks,
  Lightbulb,
  Loader2,
  CheckCircle2,
  X,
  Settings2,
  Zap,
  BookOpen,
  Target,
  GraduationCap,
  AlertCircle,
  Copy,
  Type
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/AuthContext";
import Navigation from "@/components/Navigation";
import { toast } from "sonner";
import { generateStudyContent, canUseAI } from "@/lib/ai-service";
import { extractDocumentText } from "@/lib/extract-document-text";

interface UploadedFile {
  id: string;
  name: string;
  size: number;
  uploadedAt: Date;
  status: "processing" | "ready" | "error";
  detectedChapters?: string[];
  content?: string; // Actual text content
}

interface GeneratedContent {
  id: string;
  type: "notes" | "summary" | "questions";
  title: string;
  content: string;
  createdAt: Date;
  settings: any;
  isRealAI?: boolean; // Whether generated by real AI or mock
}

interface QuizQuestion {
  question: string;
  type: 'multiple_choice' | 'true_false' | 'short_answer' | 'essay' | 'fill_blank';
  options: string[];
  answer: string;
  explanation?: string;
}

export default function AIStudyTools() {
  const navigate = useNavigate();
  const { logout, isDemo } = useAuth();
  const [uploadedFiles, setUploadedFiles] = useState<UploadedFile[]>(isDemo ? [
    {
      id: "f1",
      name: "Chapter_3_Cell_Biology.pdf",
      size: 2400000,
      uploadedAt: new Date("2026-01-18T10:30:00"),
      status: "ready",
      detectedChapters: ["Cell Structure", "Organelles", "Cell Membrane", "Transport Mechanisms"]
    },
    {
      id: "f2",
      name: "Genetics_Lecture_Notes.pdf",
      size: 1800000,
      uploadedAt: new Date("2026-01-19T14:20:00"),
      status: "ready",
      detectedChapters: ["DNA Structure", "Replication", "Transcription", "Translation"],
      content: "DNA (deoxyribonucleic acid) is the hereditary material in humans and almost all other organisms. DNA structure consists of two strands forming a double helix. The four bases are adenine (A), guanine (G), cytosine (C), and thymine (T). DNA replication is the process by which DNA makes a copy of itself during cell division."
    }
  ] : []);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState("upload");
  const [generatedContent, setGeneratedContent] = useState<GeneratedContent[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [quizStates, setQuizStates] = useState<Record<string, { answers: Record<number, string>; submitted: boolean }>>({}); 

  // Text input for direct content entry (alternative to file upload)
  const [directTextInput, setDirectTextInput] = useState("");
  const [inputMode, setInputMode] = useState<"file" | "text">("file");

  // Notes settings
  const [notesFormat, setNotesFormat] = useState<"bullet" | "paragraph" | "mindmap" | "cornell">("bullet");
  const [notesDetail, setNotesDetail] = useState<"concise" | "detailed" | "comprehensive">("detailed");
  const [includeExamples, setIncludeExamples] = useState(true);
  const [includeDiagrams, setIncludeDiagrams] = useState(true);

  // Summary settings
  const [summaryLength, setSummaryLength] = useState<"brief" | "moderate" | "detailed">("moderate");
  const [summaryFocus, setSummaryFocus] = useState<string[]>(["key_concepts", "definitions"]);
  const [includeKeyTerms, setIncludeKeyTerms] = useState(true);

  // Question settings
  const [questionDifficulty, setQuestionDifficulty] = useState<"easy" | "medium" | "hard" | "mixed">("medium");
  const [questionCount, setQuestionCount] = useState(10);
  const [questionTypes, setQuestionTypes] = useState<string[]>(["multiple_choice"]);
  const [selectedChapters, setSelectedChapters] = useState<string[]>([]);
  const [practiceMode, setPracticeMode] = useState<"practice" | "test">("practice");
  const [includeExplanations, setIncludeExplanations] = useState(true);
  const [timeLimit, setTimeLimit] = useState(0); // 0 = no limit

  // Get the content to use for generation
  const getSourceContent = (): string | null => {
    if (inputMode === "text") {
      return directTextInput.trim() || null;
    }
    const file = uploadedFiles.find(f => f.id === selectedFile);
    return file?.content || null;
  };

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files) {
      Array.from(files).forEach(async (file) => {
        const newFile: UploadedFile = {
          id: `f${Date.now()}-${Math.random()}`,
          name: file.name,
          size: file.size,
          uploadedAt: new Date(),
          status: "processing"
        };
        setUploadedFiles(prev => [...prev, newFile]);
        
        try {
          // Use proper document extraction (mammoth for docx, pdfjs for pdf, etc.)
          const textContent = await extractDocumentText(file);
          setUploadedFiles(prev => prev.map(f => 
            f.id === newFile.id 
              ? { 
                  ...f, 
                  status: "ready" as const,
                  content: textContent || undefined,
                  detectedChapters: textContent 
                    ? ["Section 1", "Section 2", "Section 3"] 
                    : undefined
                }
              : f
          ));
          // Auto-select the newly uploaded file
          setSelectedFile(newFile.id);
          toast.success(`${file.name} processed successfully!`);
        } catch (err: any) {
          console.error(`Failed to extract text from ${file.name}:`, err);
          setUploadedFiles(prev => prev.map(f => 
            f.id === newFile.id 
              ? { ...f, status: "error" as const }
              : f
          ));
          toast.error(err?.message || `Failed to read ${file.name}. Try pasting the text directly.`);
        }
      });
    }
  };

  const deleteFile = (fileId: string) => {
    setUploadedFiles(prev => prev.filter(f => f.id !== fileId));
    if (selectedFile === fileId) {
      setSelectedFile(null);
    }
    toast.success("File deleted");
  };

  // Generate notes using real AI or mock (for demo mode)
  const generateNotes = async () => {
    const content = getSourceContent();
    if (!content) {
      toast.error(inputMode === "text" 
        ? "Please enter some text content first" 
        : "Please select a file first");
      return;
    }

    setIsGenerating(true);
    const file = uploadedFiles.find(f => f.id === selectedFile);
    const contentTitle = inputMode === "text" ? "Pasted Text" : file?.name || "Content";

    // Check if user can use real AI (needs real auth, not demo)
    const { canUse } = await canUseAI();

    if (canUse && !isDemo) {
      // Use REAL AI via Edge Function
      try {
        const result = await generateStudyContent("notes", content, {
          format: notesFormat,
          detailLevel: notesDetail,
          includeExamples,
        });

        if (result.success && result.content) {
          const newNotes: GeneratedContent = {
            id: `g${Date.now()}`,
            type: "notes",
            title: `Study Notes - ${contentTitle}`,
            content: result.content,
            createdAt: new Date(),
            settings: { format: notesFormat, detail: notesDetail, examples: includeExamples },
            isRealAI: true,
          };
          setGeneratedContent(prev => [newNotes, ...prev]);
          setActiveTab("generated");
          toast.success("📝 Study notes generated with AI!");
        } else {
          toast.error(result.error || "Failed to generate notes");
        }
      } catch (error) {
        console.error("Notes generation error:", error);
        toast.error("Failed to connect to AI service");
      }
    } else {
      // Use mock data for demo mode
      setTimeout(() => {
        const newNotes: GeneratedContent = {
          id: `g${Date.now()}`,
          type: "notes",
          title: `Study Notes - ${contentTitle}`,
          content: generateMockNotes(notesFormat, notesDetail),
          createdAt: new Date(),
          settings: { format: notesFormat, detail: notesDetail, examples: includeExamples },
          isRealAI: false,
        };
        setGeneratedContent(prev => [newNotes, ...prev]);
        setActiveTab("generated");
        toast.success("📝 Study notes generated (Demo Mode)");
      }, 1500);
    }
    
    setIsGenerating(false);
  };

  // Generate summary using real AI or mock
  const generateSummary = async () => {
    const content = getSourceContent();
    if (!content) {
      toast.error(inputMode === "text" 
        ? "Please enter some text content first" 
        : "Please select a file first");
      return;
    }

    setIsGenerating(true);
    const file = uploadedFiles.find(f => f.id === selectedFile);
    const contentTitle = inputMode === "text" ? "Pasted Text" : file?.name || "Content";

    const { canUse } = await canUseAI();

    if (canUse && !isDemo) {
      // Use REAL AI
      try {
        const result = await generateStudyContent("summary", content, {
          length: summaryLength,
          focusAreas: summaryFocus,
          includeKeyTerms,
        });

        if (result.success && result.content) {
          const newSummary: GeneratedContent = {
            id: `g${Date.now()}`,
            type: "summary",
            title: `Summary - ${contentTitle}`,
            content: result.content,
            createdAt: new Date(),
            settings: { length: summaryLength, focus: summaryFocus },
            isRealAI: true,
          };
          setGeneratedContent(prev => [newSummary, ...prev]);
          setActiveTab("generated");
          toast.success("📄 Summary generated with AI!");
        } else {
          toast.error(result.error || "Failed to generate summary");
        }
      } catch (error) {
        console.error("Summary generation error:", error);
        toast.error("Failed to connect to AI service");
      }
    } else {
      // Demo mode
      setTimeout(() => {
        const newSummary: GeneratedContent = {
          id: `g${Date.now()}`,
          type: "summary",
          title: `Summary - ${contentTitle}`,
          content: generateMockSummary(summaryLength),
          createdAt: new Date(),
          settings: { length: summaryLength, focus: summaryFocus },
          isRealAI: false,
        };
        setGeneratedContent(prev => [newSummary, ...prev]);
        setActiveTab("generated");
        toast.success("📄 Summary generated (Demo Mode)");
      }, 1500);
    }

    setIsGenerating(false);
  };

  // Generate questions using real AI or mock
  const generateQuestions = async () => {
    const content = getSourceContent();
    if (!content) {
      toast.error(inputMode === "text" 
        ? "Please enter some text content first" 
        : "Please select a file first");
      return;
    }

    setIsGenerating(true);
    const file = uploadedFiles.find(f => f.id === selectedFile);
    const contentTitle = inputMode === "text" ? "Pasted Text" : file?.name || "Content";

    const addFallbackQuestions = (message: string) => {
      const newQuestions: GeneratedContent = {
        id: `g${Date.now()}`,
        type: "questions",
        title: `Practice Questions - ${contentTitle}`,
        content: generateMockQuestions(questionDifficulty, questionCount, questionTypes),
        createdAt: new Date(),
        settings: {
          difficulty: questionDifficulty,
          count: questionCount,
          types: questionTypes,
          mode: practiceMode,
        },
        isRealAI: false,
      };

      setGeneratedContent(prev => [newQuestions, ...prev]);
      setActiveTab("generated");
      toast.warning(message);
    };

    const { canUse } = await canUseAI();

    if (canUse && !isDemo) {
      // Use REAL AI
      try {
        const result = await generateStudyContent("questions", content, {
          difficulty: questionDifficulty,
          questionCount,
          questionTypes,
          includeExplanations,
        });

        if (result.success && result.content) {
          const newQuestions: GeneratedContent = {
            id: `g${Date.now()}`,
            type: "questions",
            title: `Practice Questions - ${contentTitle}`,
            content: result.content,
            createdAt: new Date(),
            settings: { 
              difficulty: questionDifficulty, 
              count: questionCount, 
              types: questionTypes,
              mode: practiceMode 
            },
            isRealAI: true,
          };
          setGeneratedContent(prev => [newQuestions, ...prev]);
          setActiveTab("generated");
          toast.success("❓ Practice questions generated with AI!");
        } else {
          console.error("Questions generation failed:", result.error);
          addFallbackQuestions("AI quiz generation is temporarily unavailable. A local interactive quiz was generated instead.");
        }
      } catch (error) {
        console.error("Questions generation error:", error);
        addFallbackQuestions("Could not connect to the AI quiz service. A local interactive quiz was generated instead.");
      }
    } else {
      // Demo mode
      setTimeout(() => {
        const newQuestions: GeneratedContent = {
          id: `g${Date.now()}`,
          type: "questions",
          title: `Practice Questions - ${contentTitle}`,
          content: generateMockQuestions(questionDifficulty, questionCount, questionTypes),
          createdAt: new Date(),
          settings: { 
            difficulty: questionDifficulty, 
            count: questionCount, 
            types: questionTypes,
            mode: practiceMode 
          },
          isRealAI: false,
        };
        setGeneratedContent(prev => [newQuestions, ...prev]);
        setActiveTab("generated");
        toast.success("❓ Practice questions generated (Demo Mode)");
      }, 1500);
    }

    setIsGenerating(false);
  };

  const downloadContent = (content: GeneratedContent) => {
    // Create downloadable text file
    const blob = new Blob([content.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${content.title.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${content.title}`);
  };

  const copyContent = (content: GeneratedContent) => {
    navigator.clipboard.writeText(content.content);
    toast.success("Copied to clipboard!");
  };

  const formatFileSize = (bytes: number) => {
    return (bytes / 1024 / 1024).toFixed(2) + " MB";
  };

  const selectedFileData = uploadedFiles.find(f => f.id === selectedFile);

  return (
    <div className="flex min-h-screen bg-background">
      <Navigation activeTab="ai-tools" onTabChange={() => {}} />
      <div className="flex-1 overflow-auto pb-16 md:pb-0">
        <div className="container mx-auto p-4 md:p-8 space-y-6">
          {/* AI Mode Indicator */}
          {isDemo ? (
            <Alert className="bg-amber-500/10 border-amber-500/30">
              <AlertCircle className="w-4 h-4 text-amber-400" />
              <AlertDescription className="text-amber-200">
                <strong>Demo Mode:</strong> Using simulated AI responses. Log in with a real account to use actual AI powered by Groq.
              </AlertDescription>
            </Alert>
          ) : (
            <Alert className="bg-emerald-500/10 border-emerald-500/30">
              <Sparkles className="w-4 h-4 text-emerald-400" />
              <AlertDescription className="text-emerald-200">
                <strong>AI Powered:</strong> Using Groq's llama-3.3-70b model for real AI generation. Free and fast!
              </AlertDescription>
            </Alert>
          )}

          {/* Header */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <h1 className="text-3xl md:text-4xl font-bold text-foreground flex items-center gap-3">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-violet-600 to-purple-600 flex items-center justify-center shrink-0">
                  <Sparkles className="w-6 h-6 text-foreground" />
                </div>
                AI Study Tools
              </h1>
              <p className="text-muted-foreground mt-2">
                Upload your study materials and let AI help you learn better
              </p>
            </div>
            <Badge className="bg-violet-600/20 text-violet-400 border-violet-600/30 text-sm px-4 py-2 shrink-0">
              <Zap className="w-4 h-4 mr-2" />
              Powered by AI
            </Badge>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <Card className="bg-card/80 border-border backdrop-blur">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Materials Uploaded</p>
                    <p className="text-2xl font-bold text-foreground mt-1">{uploadedFiles.length}</p>
                  </div>
                  <Upload className="w-8 h-8 text-violet-400" />
                </div>
              </CardContent>
            </Card>
            <Card className="bg-card/80 border-border backdrop-blur">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Content Generated</p>
                    <p className="text-2xl font-bold text-foreground mt-1">{generatedContent.length}</p>
                  </div>
                  <Brain className="w-8 h-8 text-emerald-400" />
                </div>
              </CardContent>
            </Card>
            <Card className="bg-card/80 border-border backdrop-blur">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Total Storage</p>
                    <p className="text-2xl font-bold text-foreground mt-1">
                      {formatFileSize(uploadedFiles.reduce((sum, f) => sum + f.size, 0))}
                    </p>
                  </div>
                  <FileText className="w-8 h-8 text-blue-400" />
                </div>
              </CardContent>
            </Card>
            <Card className="bg-card/80 border-border backdrop-blur">
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Study Sessions</p>
                    <p className="text-2xl font-bold text-foreground mt-1">{isDemo ? 12 : generatedContent.length}</p>
                  </div>
                  <GraduationCap className="w-8 h-8 text-amber-400" />
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Main Content */}
          <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
            <div className="overflow-x-auto pb-1">
            <TabsList className="bg-card/80 border border-border min-w-max">
              <TabsTrigger value="upload">
                <Upload className="w-4 h-4 mr-2" />
                Upload & Manage
              </TabsTrigger>
              <TabsTrigger value="notes">
                <FileText className="w-4 h-4 mr-2" />
                Generate Notes
              </TabsTrigger>
              <TabsTrigger value="summary">
                <MessageSquare className="w-4 h-4 mr-2" />
                Create Summary
              </TabsTrigger>
              <TabsTrigger value="questions">
                <ListChecks className="w-4 h-4 mr-2" />
                Practice Questions
              </TabsTrigger>
              <TabsTrigger value="generated">
                <Sparkles className="w-4 h-4 mr-2" />
                My Content ({generatedContent.length})
              </TabsTrigger>
            </TabsList>
            </div>

            {/* Upload Tab */}
            <TabsContent value="upload" className="space-y-6">
              {/* Input Mode Toggle */}
              <Card className="bg-card/80 border-border backdrop-blur">
                <CardHeader>
                  <CardTitle className="text-foreground">Choose Input Method</CardTitle>
                  <CardDescription>
                    Upload a file or paste text directly
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex gap-4">
                    <Button
                      variant={inputMode === "file" ? "default" : "outline"}
                      onClick={() => setInputMode("file")}
                      className={inputMode === "file" ? "bg-violet-600 hover:bg-violet-700" : ""}
                    >
                      <Upload className="w-4 h-4 mr-2" />
                      Upload File
                    </Button>
                    <Button
                      variant={inputMode === "text" ? "default" : "outline"}
                      onClick={() => setInputMode("text")}
                      className={inputMode === "text" ? "bg-violet-600 hover:bg-violet-700" : ""}
                    >
                      <Type className="w-4 h-4 mr-2" />
                      Paste Text
                    </Button>
                  </div>
                </CardContent>
              </Card>

              {inputMode === "text" ? (
                /* Text Input Mode */
                <Card className="bg-card/80 border-border backdrop-blur">
                  <CardHeader>
                    <CardTitle className="text-foreground flex items-center gap-2">
                      <Type className="w-5 h-5" />
                      Paste Your Study Content
                    </CardTitle>
                    <CardDescription>
                      Paste text from your notes, textbooks, or lecture slides. The AI will generate study materials from this content.
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <Textarea
                      placeholder="Paste your study content here... (e.g., lecture notes, textbook excerpts, article text)"
                      value={directTextInput}
                      onChange={(e) => setDirectTextInput(e.target.value)}
                      className="min-h-[300px] bg-muted/50 border-border text-foreground placeholder:text-muted-foreground/60 resize-y"
                    />
                    <div className="flex items-center justify-between">
                      <p className="text-sm text-muted-foreground">
                        {directTextInput.length} characters
                        {directTextInput.length > 100 && (
                          <span className="text-emerald-400 ml-2">✓ Ready to generate</span>
                        )}
                      </p>
                      {directTextInput.length > 0 && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => setDirectTextInput("")}
                          className="text-red-400 hover:text-red-300"
                        >
                          <Trash2 className="w-4 h-4 mr-1" />
                          Clear
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ) : (
                /* File Upload Mode */
                <Card className="bg-card/80 border-border backdrop-blur">
                  <CardHeader>
                    <CardTitle className="text-foreground">Upload Study Materials</CardTitle>
                    <CardDescription>
                      Upload PDFs, Word documents, or PowerPoint slides from your courses
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="border-2 border-dashed border-border rounded-lg p-8 text-center hover:border-violet-600 transition-colors cursor-pointer bg-muted/30">
                      <input
                        type="file"
                        id="file-upload"
                        className="hidden"
                        accept=".pdf,.doc,.docx,.ppt,.pptx"
                        multiple
                        onChange={handleFileUpload}
                      />
                      <label htmlFor="file-upload" className="cursor-pointer">
                        <Upload className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                        <p className="text-foreground font-medium mb-2">
                          Click to upload or drag and drop
                        </p>
                        <p className="text-sm text-muted-foreground">
                          PDF, DOC, DOCX, PPT, PPTX (Max 50MB each)
                        </p>
                      </label>
                    </div>

                    <Alert className="bg-blue-500/10 border-blue-500/30">
                      <AlertCircle className="w-4 h-4 text-blue-400" />
                      <AlertDescription className="text-blue-200 text-sm">
                        <strong>Supported formats:</strong> PDF, DOCX, DOC, and TXT files. Text is extracted automatically for AI analysis.
                      </AlertDescription>
                    </Alert>

                    <Separator className="bg-border" />

                    <div className="space-y-3">
                      <h3 className="text-foreground font-semibold flex items-center gap-2">
                        <FileText className="w-5 h-5" />
                        My Materials ({uploadedFiles.length})
                      </h3>
                      {uploadedFiles.map(file => (
                        <div
                          key={file.id}
                          className={`p-4 rounded-lg border transition-all cursor-pointer ${
                            selectedFile === file.id && inputMode === "file"
                              ? "bg-violet-600/20 border-violet-600"
                              : "bg-muted/50 border-border hover:border-slate-600"
                          }`}
                          onClick={() => {
                            setSelectedFile(file.id);
                            setInputMode("file");
                          }}
                        >
                          <div className="flex items-start justify-between">
                            <div className="flex-1">
                              <div className="flex items-center gap-3 mb-2">
                                <FileText className="w-5 h-5 text-violet-400" />
                                <p className="text-foreground font-medium">{file.name}</p>
                                {file.status === "processing" && (
                                  <Badge className="bg-blue-600/20 text-blue-400 border-blue-600/30">
                                    <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                                    Processing
                                  </Badge>
                                )}
                                {file.status === "ready" && (
                                  <Badge className="bg-emerald-600/20 text-emerald-400 border-emerald-600/30">
                                    <CheckCircle2 className="w-3 h-3 mr-1" />
                                    Ready
                                  </Badge>
                                )}
                                {file.content && (
                                  <Badge className="bg-violet-600/20 text-violet-400 border-violet-600/30">
                                    Has Content
                                  </Badge>
                                )}
                              </div>
                              <p className="text-sm text-muted-foreground mb-3">
                                {formatFileSize(file.size)} • Uploaded {file.uploadedAt.toLocaleDateString()}
                              </p>
                              {file.detectedChapters && (
                              <div className="flex flex-wrap gap-2">
                                {file.detectedChapters.map((chapter, idx) => (
                                  <Badge key={idx} variant="outline" className="text-xs">
                                    {chapter}
                                  </Badge>
                                ))}
                              </div>
                            )}
                          </div>
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={(e) => {
                              e.stopPropagation();
                              deleteFile(file.id);
                            }}
                            className="text-red-400 hover:text-red-300 hover:bg-red-500/10"
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
              )}
            </TabsContent>

            {/* Notes Generation Tab */}
            <TabsContent value="notes" className="space-y-6">
              {!getSourceContent() ? (
                <Alert className="bg-yellow-500/10 border-yellow-500/30">
                  <Lightbulb className="w-4 h-4 text-yellow-400" />
                  <AlertDescription className="text-yellow-200">
                    {inputMode === "text" 
                      ? "Please paste some text content in the \"Upload & Manage\" tab first"
                      : "Please select a material from the \"Upload & Manage\" tab first"}
                  </AlertDescription>
                </Alert>
              ) : (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  {/* Settings Panel */}
                  <Card className="lg:col-span-1 bg-card/80 border-border backdrop-blur">
                    <CardHeader>
                      <CardTitle className="text-foreground flex items-center gap-2">
                        <Settings2 className="w-5 h-5" />
                        Note Settings
                      </CardTitle>
                      <CardDescription>
                        Customize how your notes are generated
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                      {/* Note Format */}
                      <div className="space-y-3">
                        <Label className="text-foreground">Note Format</Label>
                        <RadioGroup value={notesFormat} onValueChange={(v: any) => setNotesFormat(v)}>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border hover:border-violet-600 transition-colors">
                            <RadioGroupItem value="bullet" id="bullet" />
                            <Label htmlFor="bullet" className="flex-1 cursor-pointer text-foreground/80">
                              Bullet Points
                              <p className="text-xs text-muted-foreground mt-1">Quick, scannable format</p>
                            </Label>
                          </div>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border hover:border-violet-600 transition-colors">
                            <RadioGroupItem value="paragraph" id="paragraph" />
                            <Label htmlFor="paragraph" className="flex-1 cursor-pointer text-foreground/80">
                              Paragraphs
                              <p className="text-xs text-muted-foreground mt-1">Detailed explanations</p>
                            </Label>
                          </div>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border hover:border-violet-600 transition-colors">
                            <RadioGroupItem value="mindmap" id="mindmap" />
                            <Label htmlFor="mindmap" className="flex-1 cursor-pointer text-foreground/80">
                              Mind Map
                              <p className="text-xs text-muted-foreground mt-1">Visual connections</p>
                            </Label>
                          </div>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border hover:border-violet-600 transition-colors">
                            <RadioGroupItem value="cornell" id="cornell" />
                            <Label htmlFor="cornell" className="flex-1 cursor-pointer text-foreground/80">
                              Cornell Notes
                              <p className="text-xs text-muted-foreground mt-1">Structured system</p>
                            </Label>
                          </div>
                        </RadioGroup>
                      </div>

                      <Separator className="bg-border" />

                      {/* Detail Level */}
                      <div className="space-y-3">
                        <Label className="text-foreground">Detail Level</Label>
                        <Select value={notesDetail} onValueChange={(v: any) => setNotesDetail(v)}>
                          <SelectTrigger className="bg-muted border-border text-foreground">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="concise">Concise - Key points only</SelectItem>
                            <SelectItem value="detailed">Detailed - Balanced coverage</SelectItem>
                            <SelectItem value="comprehensive">Comprehensive - Everything</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>

                      <Separator className="bg-border" />

                      {/* Additional Options */}
                      <div className="space-y-3">
                        <Label className="text-foreground">Include</Label>
                        <div className="space-y-3">
                          <div className="flex items-center space-x-2">
                            <Checkbox 
                              id="examples" 
                              checked={includeExamples}
                              onCheckedChange={(c) => setIncludeExamples(c as boolean)}
                            />
                            <Label htmlFor="examples" className="text-foreground/80 cursor-pointer">
                              Examples & Case Studies
                            </Label>
                          </div>
                          <div className="flex items-center space-x-2">
                            <Checkbox 
                              id="diagrams" 
                              checked={includeDiagrams}
                              onCheckedChange={(c) => setIncludeDiagrams(c as boolean)}
                            />
                            <Label htmlFor="diagrams" className="text-foreground/80 cursor-pointer">
                              Diagram Descriptions
                            </Label>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  {/* Preview Panel */}
                  <Card className="lg:col-span-2 bg-card/80 border-border backdrop-blur">
                    <CardHeader>
                      <CardTitle className="text-foreground">Selected Material</CardTitle>
                      <CardDescription>
                        {selectedFileData?.name}
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      {selectedFileData?.detectedChapters && (
                        <div>
                          <Label className="text-foreground mb-2 block">Detected Topics</Label>
                          <div className="flex flex-wrap gap-2">
                            {selectedFileData.detectedChapters.map((chapter, idx) => (
                              <Badge key={idx} className="bg-violet-600/20 text-violet-300 border-violet-600/30">
                                {chapter}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      )}

                      <Alert className="bg-blue-500/10 border-blue-500/30">
                        <Sparkles className="w-4 h-4 text-blue-400" />
                        <AlertDescription className="text-blue-200">
                          AI will generate {notesDetail} notes in {notesFormat} format with{" "}
                          {includeExamples && "examples"}{includeExamples && includeDiagrams && " and "}{includeDiagrams && "diagrams"}
                        </AlertDescription>
                      </Alert>

                      <Button 
                        onClick={generateNotes} 
                        className="w-full bg-violet-600 hover:bg-violet-700 text-foreground"
                        size="lg"
                        disabled={isGenerating}
                      >
                        {isGenerating ? (
                          <>
                            <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                            Generating Notes...
                          </>
                        ) : (
                          <>
                            <Sparkles className="w-5 h-5 mr-2" />
                            Generate Study Notes
                          </>
                        )}
                      </Button>
                    </CardContent>
                  </Card>
                </div>
              )}
            </TabsContent>

            {/* Summary Generation Tab */}
            <TabsContent value="summary" className="space-y-6">
              {!getSourceContent() ? (
                <Alert className="bg-yellow-500/10 border-yellow-500/30">
                  <Lightbulb className="w-4 h-4 text-yellow-400" />
                  <AlertDescription className="text-yellow-200">
                    {inputMode === "text" 
                      ? "Please paste some text content in the \"Upload & Manage\" tab first"
                      : "Please select a material from the \"Upload & Manage\" tab first"}
                  </AlertDescription>
                </Alert>
              ) : (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  {/* Settings Panel */}
                  <Card className="lg:col-span-1 bg-card/80 border-border backdrop-blur">
                    <CardHeader>
                      <CardTitle className="text-foreground flex items-center gap-2">
                        <Settings2 className="w-5 h-5" />
                        Summary Settings
                      </CardTitle>
                      <CardDescription>
                        Customize your summary
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                      {/* Length */}
                      <div className="space-y-3">
                        <Label className="text-foreground">Summary Length</Label>
                        <RadioGroup value={summaryLength} onValueChange={(v: any) => setSummaryLength(v)}>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border">
                            <RadioGroupItem value="brief" id="brief" />
                            <Label htmlFor="brief" className="flex-1 cursor-pointer text-foreground/80">
                              Brief (1-2 paragraphs)
                            </Label>
                          </div>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border">
                            <RadioGroupItem value="moderate" id="moderate" />
                            <Label htmlFor="moderate" className="flex-1 cursor-pointer text-foreground/80">
                              Moderate (3-5 paragraphs)
                            </Label>
                          </div>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border">
                            <RadioGroupItem value="detailed" id="detailed-summary" />
                            <Label htmlFor="detailed-summary" className="flex-1 cursor-pointer text-foreground/80">
                              Detailed (Full overview)
                            </Label>
                          </div>
                        </RadioGroup>
                      </div>

                      <Separator className="bg-border" />

                      {/* Focus Areas */}
                      <div className="space-y-3">
                        <Label className="text-foreground">Focus On</Label>
                        <div className="space-y-2">
                          {[
                            { id: "key_concepts", label: "Key Concepts" },
                            { id: "definitions", label: "Definitions" },
                            { id: "processes", label: "Processes & Methods" },
                            { id: "relationships", label: "Relationships & Connections" },
                            { id: "applications", label: "Real-world Applications" }
                          ].map(item => (
                            <div key={item.id} className="flex items-center space-x-2">
                              <Checkbox 
                                id={item.id}
                                checked={summaryFocus.includes(item.id)}
                                onCheckedChange={(checked) => {
                                  if (checked) {
                                    setSummaryFocus([...summaryFocus, item.id]);
                                  } else {
                                    setSummaryFocus(summaryFocus.filter(f => f !== item.id));
                                  }
                                }}
                              />
                              <Label htmlFor={item.id} className="text-foreground/80 cursor-pointer">
                                {item.label}
                              </Label>
                            </div>
                          ))}
                        </div>
                      </div>

                      <Separator className="bg-border" />

                      <div className="flex items-center space-x-2">
                        <Checkbox 
                          id="keyterms" 
                          checked={includeKeyTerms}
                          onCheckedChange={(c) => setIncludeKeyTerms(c as boolean)}
                        />
                        <Label htmlFor="keyterms" className="text-foreground/80 cursor-pointer">
                          Include Key Terms Glossary
                        </Label>
                      </div>
                    </CardContent>
                  </Card>

                  {/* Preview Panel */}
                  <Card className="lg:col-span-2 bg-card/80 border-border backdrop-blur">
                    <CardHeader>
                      <CardTitle className="text-foreground">Generate Summary</CardTitle>
                      <CardDescription>
                        {selectedFileData?.name}
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <Alert className="bg-blue-500/10 border-blue-500/30">
                        <MessageSquare className="w-4 h-4 text-blue-400" />
                        <AlertDescription className="text-blue-200">
                          AI will create a {summaryLength} summary focusing on {summaryFocus.length} selected areas
                        </AlertDescription>
                      </Alert>

                      <Button 
                        onClick={generateSummary} 
                        className="w-full bg-emerald-600 hover:bg-emerald-700 text-foreground"
                        size="lg"
                        disabled={isGenerating}
                      >
                        {isGenerating ? (
                          <>
                            <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                            Creating Summary...
                          </>
                        ) : (
                          <>
                            <MessageSquare className="w-5 h-5 mr-2" />
                            Generate Summary
                          </>
                        )}
                      </Button>
                    </CardContent>
                  </Card>
                </div>
              )}
            </TabsContent>

            {/* Questions Generation Tab */}
            <TabsContent value="questions" className="space-y-6">
              {!getSourceContent() ? (
                <Alert className="bg-yellow-500/10 border-yellow-500/30">
                  <Lightbulb className="w-4 h-4 text-yellow-400" />
                  <AlertDescription className="text-yellow-200">
                    {inputMode === "text" 
                      ? "Please paste some text content in the \"Upload & Manage\" tab first"
                      : "Please select a material from the \"Upload & Manage\" tab first"}
                  </AlertDescription>
                </Alert>
              ) : (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  {/* Settings Panel */}
                  <Card className="lg:col-span-1 bg-card/80 border-border backdrop-blur">
                    <CardHeader>
                      <CardTitle className="text-foreground flex items-center gap-2">
                        <Settings2 className="w-5 h-5" />
                        Question Settings
                      </CardTitle>
                      <CardDescription>
                        Full customization for practice
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                      {/* Difficulty */}
                      <div className="space-y-3">
                        <Label className="text-foreground">Difficulty Level</Label>
                        <Select value={questionDifficulty} onValueChange={(v: any) => setQuestionDifficulty(v)}>
                          <SelectTrigger className="bg-muted border-border text-foreground">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="easy">Easy - Basic concepts</SelectItem>
                            <SelectItem value="medium">Medium - Moderate thinking</SelectItem>
                            <SelectItem value="hard">Hard - Advanced analysis</SelectItem>
                            <SelectItem value="mixed">Mixed - All levels</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>

                      {/* Number of Questions */}
                      <div className="space-y-3">
                        <div className="flex items-center justify-between">
                          <Label className="text-foreground">Number of Questions</Label>
                          <Badge variant="outline" className="text-violet-400">
                            {questionCount}
                          </Badge>
                        </div>
                        <Slider 
                          value={[questionCount]} 
                          onValueChange={(v) => setQuestionCount(v[0])}
                          min={5}
                          max={50}
                          step={5}
                          className="py-4"
                        />
                        <div className="flex justify-between text-xs text-muted-foreground">
                          <span>5</span>
                          <span>25</span>
                          <span>50</span>
                        </div>
                      </div>

                      <Separator className="bg-border" />

                      {/* Question Types */}
                      <div className="space-y-3">
                        <Label className="text-foreground">Question Types</Label>
                        <div className="space-y-2">
                          {[
                            { id: "multiple_choice", label: "Multiple Choice" },
                            { id: "true_false", label: "True/False" },
                            { id: "short_answer", label: "Short Answer" },
                            { id: "essay", label: "Essay Questions" },
                            { id: "fill_blank", label: "Fill in the Blanks" }
                          ].map(type => (
                            <div key={type.id} className="flex items-center space-x-2">
                              <Checkbox 
                                id={type.id}
                                checked={questionTypes.includes(type.id)}
                                onCheckedChange={(checked) => {
                                  if (checked) {
                                    setQuestionTypes([...questionTypes, type.id]);
                                  } else {
                                    setQuestionTypes(questionTypes.filter(t => t !== type.id));
                                  }
                                }}
                              />
                              <Label htmlFor={type.id} className="text-foreground/80 cursor-pointer">
                                {type.label}
                              </Label>
                            </div>
                          ))}
                        </div>
                      </div>

                      <Separator className="bg-border" />

                      {/* Chapter Selection */}
                      {selectedFileData?.detectedChapters && (
                        <div className="space-y-3">
                          <Label className="text-foreground">Select Topics (Optional)</Label>
                          <div className="space-y-2 max-h-40 overflow-y-auto">
                            {selectedFileData.detectedChapters.map((chapter, idx) => (
                              <div key={idx} className="flex items-center space-x-2">
                                <Checkbox 
                                  id={`chapter-${idx}`}
                                  checked={selectedChapters.includes(chapter)}
                                  onCheckedChange={(checked) => {
                                    if (checked) {
                                      setSelectedChapters([...selectedChapters, chapter]);
                                    } else {
                                      setSelectedChapters(selectedChapters.filter(c => c !== chapter));
                                    }
                                  }}
                                />
                                <Label htmlFor={`chapter-${idx}`} className="text-foreground/80 cursor-pointer text-sm">
                                  {chapter}
                                </Label>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      <Separator className="bg-border" />

                      {/* Mode */}
                      <div className="space-y-3">
                        <Label className="text-foreground">Mode</Label>
                        <RadioGroup value={practiceMode} onValueChange={(v: any) => setPracticeMode(v)}>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border">
                            <RadioGroupItem value="practice" id="practice" />
                            <Label htmlFor="practice" className="flex-1 cursor-pointer text-foreground/80">
                              Practice Mode
                              <p className="text-xs text-muted-foreground mt-1">Instant feedback</p>
                            </Label>
                          </div>
                          <div className="flex items-center space-x-2 p-3 rounded-lg border border-border">
                            <RadioGroupItem value="test" id="test" />
                            <Label htmlFor="test" className="flex-1 cursor-pointer text-foreground/80">
                              Test Mode
                              <p className="text-xs text-muted-foreground mt-1">Grade at end</p>
                            </Label>
                          </div>
                        </RadioGroup>
                      </div>

                      {/* Additional Options */}
                      <div className="space-y-2">
                        <div className="flex items-center space-x-2">
                          <Checkbox 
                            id="explanations" 
                            checked={includeExplanations}
                            onCheckedChange={(c) => setIncludeExplanations(c as boolean)}
                          />
                          <Label htmlFor="explanations" className="text-foreground/80 cursor-pointer">
                            Include Answer Explanations
                          </Label>
                        </div>
                      </div>

                      {/* Time Limit */}
                      <div className="space-y-3">
                        <div className="flex items-center justify-between">
                          <Label className="text-foreground">Time Limit (minutes)</Label>
                          <Badge variant="outline" className="text-violet-400">
                            {timeLimit === 0 ? "Unlimited" : `${timeLimit} min`}
                          </Badge>
                        </div>
                        <Slider 
                          value={[timeLimit]} 
                          onValueChange={(v) => setTimeLimit(v[0])}
                          min={0}
                          max={120}
                          step={5}
                          className="py-4"
                        />
                      </div>
                    </CardContent>
                  </Card>

                  {/* Preview Panel */}
                  <Card className="lg:col-span-2 bg-card/80 border-border backdrop-blur">
                    <CardHeader>
                      <CardTitle className="text-foreground">Generate Practice Questions</CardTitle>
                      <CardDescription>
                        {selectedFileData?.name}
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      {/* Configuration Summary */}
                      <div className="grid grid-cols-2 gap-3">
                        <div className="p-3 rounded-lg bg-muted/50 border border-border">
                          <p className="text-xs text-muted-foreground mb-1">Questions</p>
                          <p className="text-lg font-semibold text-foreground">{questionCount}</p>
                        </div>
                        <div className="p-3 rounded-lg bg-muted/50 border border-border">
                          <p className="text-xs text-muted-foreground mb-1">Difficulty</p>
                          <p className="text-lg font-semibold text-foreground capitalize">{questionDifficulty}</p>
                        </div>
                        <div className="p-3 rounded-lg bg-muted/50 border border-border">
                          <p className="text-xs text-muted-foreground mb-1">Types</p>
                          <p className="text-lg font-semibold text-foreground">{questionTypes.length}</p>
                        </div>
                        <div className="p-3 rounded-lg bg-muted/50 border border-border">
                          <p className="text-xs text-muted-foreground mb-1">Mode</p>
                          <p className="text-lg font-semibold text-foreground capitalize">{practiceMode}</p>
                        </div>
                      </div>

                      {selectedChapters.length > 0 && (
                        <Alert className="bg-violet-500/10 border-violet-500/30">
                          <Target className="w-4 h-4 text-violet-400" />
                          <AlertDescription className="text-violet-200">
                            Questions will focus on {selectedChapters.length} selected topic(s)
                          </AlertDescription>
                        </Alert>
                      )}

                      <Alert className="bg-blue-500/10 border-blue-500/30">
                        <ListChecks className="w-4 h-4 text-blue-400" />
                        <AlertDescription className="text-blue-200">
                          AI will generate {questionCount} {questionDifficulty} questions
                          {includeExplanations && " with detailed explanations"}
                          {timeLimit > 0 && ` (${timeLimit} min time limit)`}
                        </AlertDescription>
                      </Alert>

                      <Button 
                        onClick={generateQuestions} 
                        className="w-full bg-blue-600 hover:bg-blue-700 text-foreground"
                        size="lg"
                        disabled={isGenerating || questionTypes.length === 0}
                      >
                        {isGenerating ? (
                          <>
                            <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                            Generating Questions...
                          </>
                        ) : (
                          <>
                            <ListChecks className="w-5 h-5 mr-2" />
                            Generate Practice Questions
                          </>
                        )}
                      </Button>

                      {questionTypes.length === 0 && (
                        <p className="text-sm text-yellow-400 text-center">
                          Please select at least one question type
                        </p>
                      )}
                    </CardContent>
                  </Card>
                </div>
              )}
            </TabsContent>

            {/* Generated Content Tab */}
            <TabsContent value="generated" className="space-y-4">
              {generatedContent.length === 0 ? (
                <Card className="bg-card/80 border-border backdrop-blur">
                  <CardContent className="pt-12 pb-12 text-center">
                    <BookOpen className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
                    <h3 className="text-xl font-semibold text-foreground mb-2">No Content Generated Yet</h3>
                    <p className="text-muted-foreground max-w-md mx-auto">
                      Upload materials and use the AI tools to generate study notes, summaries, and practice questions
                    </p>
                  </CardContent>
                </Card>
              ) : (
                <div className="space-y-4">
                  {generatedContent.map(content => (
                    <Card key={content.id} className="bg-card/80 border-border backdrop-blur hover:border-violet-600 transition-colors">
                      <CardHeader>
                        <div className="flex items-start justify-between">
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              {content.type === "notes" && <FileText className="w-5 h-5 text-violet-400" />}
                              {content.type === "summary" && <MessageSquare className="w-5 h-5 text-emerald-400" />}
                              {content.type === "questions" && <ListChecks className="w-5 h-5 text-blue-400" />}
                              <CardTitle className="text-foreground">{content.title}</CardTitle>
                            </div>
                            <CardDescription>
                              Created {content.createdAt.toLocaleString()}
                            </CardDescription>
                          </div>
                          <div className="flex items-center gap-2">
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => downloadContent(content)}
                              className="border-border"
                            >
                              <Download className="w-4 h-4 mr-2" />
                              Download
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => setGeneratedContent(prev => prev.filter(c => c.id !== content.id))}
                              className="text-red-400 hover:text-red-300"
                            >
                              <X className="w-4 h-4" />
                            </Button>
                          </div>
                        </div>
                      </CardHeader>
                      <CardContent>
                        {content.type === "questions" ? (
                          <QuizContent
                            content={content}
                            quizState={quizStates[content.id] || { answers: {}, submitted: false }}
                            onAnswerSelect={(qIdx, answer) =>
                              setQuizStates(prev => ({
                                ...prev,
                                [content.id]: {
                                  ...(prev[content.id] || { answers: {}, submitted: false }),
                                  answers: { ...(prev[content.id]?.answers || {}), [qIdx]: answer },
                                },
                              }))
                            }
                            onSubmit={() =>
                              setQuizStates(prev => ({
                                ...prev,
                                [content.id]: { ...(prev[content.id] || { answers: {}, submitted: false }), submitted: true },
                              }))
                            }
                            onRetry={() =>
                              setQuizStates(prev => ({ ...prev, [content.id]: { answers: {}, submitted: false } }))
                            }
                          />
                        ) : (
                          <div className="p-4 rounded-lg bg-muted/50 border border-border">
                            <pre className="text-sm text-foreground/70 whitespace-pre-wrap font-mono">
                              {content.content}
                            </pre>
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  );
}

// Mock content generators
function generateMockNotes(format: string, detail: string) {
  return `# Study Notes - Cell Biology (${format} format, ${detail} detail)

## Cell Structure
${format === "bullet" ? `
• Cells are the basic unit of life
• Two main types: Prokaryotic and Eukaryotic
• Prokaryotes: No nucleus, simple structure
• Eukaryotes: Membrane-bound nucleus and organelles
` : `
Cells represent the fundamental unit of all living organisms. There are two primary categories of cells: prokaryotic and eukaryotic. Prokaryotic cells lack a membrane-bound nucleus and possess a relatively simple internal structure. In contrast, eukaryotic cells contain a well-defined nucleus enclosed by a nuclear membrane, along with various specialized organelles.
`}

## Cell Membrane
${format === "bullet" ? `
• Phospholipid bilayer structure
• Selectively permeable
• Contains proteins for transport
• Maintains cell shape and protection
` : `
The cell membrane consists of a phospholipid bilayer that serves as a selectively permeable barrier. This structure controls the passage of substances in and out of the cell. Embedded proteins facilitate various transport mechanisms, while the membrane also provides structural support and protection to the cell.
`}

[AI Generated Content - Full notes would continue with all detected topics]`;
}

function generateMockSummary(length: string) {
  const brief = "This material covers fundamental concepts in cell biology, focusing on cell structure, organelles, and membrane function. Key topics include the differences between prokaryotic and eukaryotic cells, the role of various organelles in cellular processes, and transport mechanisms across membranes.";
  
  const moderate = brief + "\n\nThe content explores cell structure in detail, explaining how the phospholipid bilayer forms the foundation of the cell membrane and controls substance movement. Various organelles are discussed, including mitochondria for energy production, ribosomes for protein synthesis, and the endoplasmic reticulum for protein and lipid processing. Transport mechanisms such as diffusion, osmosis, and active transport are explained with their energy requirements and directional flow.";
  
  const detailed = moderate + "\n\nFurther analysis reveals the intricate relationships between cellular components and their functions. The material emphasizes how cellular processes are interconnected, from DNA transcription in the nucleus to protein synthesis in ribosomes and subsequent modifications in the Golgi apparatus. Real-world applications include understanding disease mechanisms, drug development targeting specific cellular pathways, and biotechnology applications in genetic engineering. The content provides a comprehensive foundation for advanced studies in molecular biology and cellular biochemistry.";
  
  return length === "brief" ? brief : length === "moderate" ? moderate : detailed;
}

function generateMockQuestions(difficulty: string, count: number, types: string[]): string {
  const bank: QuizQuestion[] = [
    { question: "What is the primary function of mitochondria?", type: "multiple_choice", options: ["Protein synthesis", "ATP production through cellular respiration", "Lipid storage", "DNA replication"], answer: "ATP production through cellular respiration", explanation: "Mitochondria generate ATP via oxidative phosphorylation — they are the powerhouse of the cell." },
    { question: "Which organelle is responsible for protein synthesis?", type: "multiple_choice", options: ["Nucleus", "Golgi apparatus", "Ribosome", "Lysosome"], answer: "Ribosome", explanation: "Ribosomes translate mRNA into proteins during the process of translation." },
    { question: "What controls what enters and exits the cell?", type: "multiple_choice", options: ["Cell wall", "Nucleus", "Cell membrane", "Cytoplasm"], answer: "Cell membrane", explanation: "The selectively permeable cell membrane regulates movement of substances in and out of the cell." },
    { question: "DNA replication occurs during which phase?", type: "multiple_choice", options: ["G1 phase", "S phase", "G2 phase", "M phase"], answer: "S phase", explanation: "DNA synthesis occurs during the S (synthesis) phase of interphase." },
    { question: "Which process converts glucose into pyruvate?", type: "multiple_choice", options: ["Krebs cycle", "Glycolysis", "Oxidative phosphorylation", "Beta oxidation"], answer: "Glycolysis", explanation: "Glycolysis breaks glucose into two pyruvate molecules in the cytoplasm." },
    { question: "The nucleus contains the genetic material of the cell.", type: "true_false", options: ["True", "False"], answer: "True", explanation: "The nucleus houses DNA organized into chromosomes and is the control center of eukaryotic cells." },
    { question: "Photosynthesis occurs in the mitochondria.", type: "true_false", options: ["True", "False"], answer: "False", explanation: "Photosynthesis occurs in chloroplasts. Mitochondria handle cellular respiration." },
    { question: "All cells have a cell wall.", type: "true_false", options: ["True", "False"], answer: "False", explanation: "Only plant cells, fungi, and some bacteria have cell walls. Animal cells only have cell membranes." },
    { question: "Describe the difference between passive and active transport.", type: "short_answer", options: [], answer: "Passive transport moves substances from high to low concentration without energy. Active transport moves substances against the gradient and requires ATP.", explanation: "The key distinction is energy requirement and direction relative to the concentration gradient." },
    { question: "What is the role of ATP in cellular processes?", type: "short_answer", options: [], answer: "ATP is the primary energy currency of the cell, providing energy for muscle contraction, active transport, and biosynthesis.", explanation: "ATP stores and transfers energy through its high-energy phosphate bonds." },
  ];

  const targetCount = Math.min(count, 10);
  const questions: QuizQuestion[] = [];
  const typeList = types.length > 0 ? types : ["multiple_choice"];

  for (let i = 0; i < targetCount; i++) {
    const preferredType = typeList[i % typeList.length];
    const pool = bank.filter(q => q.type === preferredType || (preferredType === 'essay' && q.type === 'short_answer') || (preferredType === 'fill_blank' && q.type === 'short_answer'));
    const source = pool.length > 0 ? pool : bank.filter(q => q.type === 'multiple_choice');
    questions.push(source[i % source.length]);
  }

  return JSON.stringify(questions);
}

// ─── Interactive Quiz Component ───────────────────────────────────────────────
interface QuizContentProps {
  content: GeneratedContent;
  quizState: { answers: Record<number, string>; submitted: boolean };
  onAnswerSelect: (qIdx: number, answer: string) => void;
  onSubmit: () => void;
  onRetry: () => void;
}

function QuizContent({ content, quizState, onAnswerSelect, onSubmit, onRetry }: QuizContentProps) {
  let questions: QuizQuestion[] = [];
  let parseError = false;

  try {
    questions = JSON.parse(content.content) as QuizQuestion[];
    if (!Array.isArray(questions)) throw new Error("Not array");
  } catch {
    parseError = true;
  }

  if (parseError) {
    return (
      <div className="p-4 rounded-lg bg-muted/50 border border-border">
        <pre className="text-sm text-foreground/70 whitespace-pre-wrap font-mono">{content.content}</pre>
      </div>
    );
  }

  const { answers, submitted } = quizState;

  const score = submitted
    ? questions.reduce((acc, q, i) => acc + (answers[i]?.toLowerCase() === q.answer.toLowerCase() ? 1 : 0), 0)
    : 0;

  const allAnswered = questions.every((_, i) => answers[i] !== undefined && answers[i] !== "");

  return (
    <div className="space-y-6">
      {/* Score banner */}
      {submitted && (
        <div className={`flex items-center justify-between p-4 rounded-lg border ${score / questions.length >= 0.7 ? "bg-green-50 border-green-200 dark:bg-green-950 dark:border-green-800" : "bg-orange-50 border-orange-200 dark:bg-orange-950 dark:border-orange-800"}`}>
          <span className="font-semibold text-base">
            Score: {score} / {questions.length} ({Math.round((score / questions.length) * 100)}%)
          </span>
          <button
            onClick={onRetry}
            className="px-3 py-1.5 text-sm font-medium rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
          >
            Retry
          </button>
        </div>
      )}

      {/* Questions */}
      {questions.map((q, qIdx) => {
        const selected = answers[qIdx] ?? "";
        const isCorrect = selected.toLowerCase() === q.answer.toLowerCase();

        return (
          <div key={qIdx} className="border border-border rounded-lg p-4 space-y-3">
            <p className="font-medium text-sm text-foreground">
              <span className="text-muted-foreground mr-1">{qIdx + 1}.</span> {q.question}
            </p>

            {/* Multiple choice / True-False */}
            {(q.type === "multiple_choice" || q.type === "true_false") && (
              <div className="space-y-2">
                {q.options.map((opt, oIdx) => {
                  let optClass = "flex items-center gap-2 px-3 py-2 rounded-md border cursor-pointer text-sm transition-colors ";
                  if (!submitted) {
                    optClass += selected === opt
                      ? "border-primary bg-primary/10 text-primary"
                      : "border-border hover:border-primary/50 hover:bg-muted/50 text-foreground";
                  } else {
                    const isThisCorrect = opt.toLowerCase() === q.answer.toLowerCase();
                    const isThisSelected = selected === opt;
                    if (isThisCorrect) optClass += "border-green-400 bg-green-50 text-green-800 dark:bg-green-950 dark:text-green-200 dark:border-green-600";
                    else if (isThisSelected && !isThisCorrect) optClass += "border-red-400 bg-red-50 text-red-800 dark:bg-red-950 dark:text-red-200 dark:border-red-600";
                    else optClass += "border-border text-muted-foreground opacity-60";
                  }
                  return (
                    <div
                      key={oIdx}
                      className={optClass}
                      onClick={() => !submitted && onAnswerSelect(qIdx, opt)}
                    >
                      <span className="w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 text-xs font-bold">
                        {String.fromCharCode(65 + oIdx)}
                      </span>
                      {opt}
                    </div>
                  );
                })}
              </div>
            )}

            {/* Short answer / Essay / Fill blank */}
            {(q.type === "short_answer" || q.type === "essay" || q.type === "fill_blank") && (
              <textarea
                disabled={submitted}
                value={selected}
                onChange={e => onAnswerSelect(qIdx, e.target.value)}
                rows={q.type === "essay" ? 4 : 2}
                placeholder="Type your answer here…"
                className="w-full px-3 py-2 text-sm rounded-md border border-border bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary disabled:opacity-60"
              />
            )}

            {/* Explanation after submit */}
            {submitted && q.explanation && (
              <div className={`text-xs px-3 py-2 rounded-md ${isCorrect ? "bg-green-50 text-green-700 dark:bg-green-950 dark:text-green-300" : "bg-orange-50 text-orange-700 dark:bg-orange-950 dark:text-orange-300"}`}>
                <span className="font-semibold">Explanation:</span> {q.explanation}
              </div>
            )}

            {/* Correct answer for open-ended after submit */}
            {submitted && (q.type === "short_answer" || q.type === "essay" || q.type === "fill_blank") && (
              <div className="text-xs px-3 py-2 rounded-md bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-300">
                <span className="font-semibold">Model answer:</span> {q.answer}
              </div>
            )}
          </div>
        );
      })}

      {/* Submit button */}
      {!submitted && (
        <button
          onClick={onSubmit}
          disabled={!allAnswered}
          className="w-full py-2 px-4 rounded-md bg-primary text-primary-foreground font-medium text-sm hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          Submit Quiz
        </button>
      )}
    </div>
  );
}
